title: Zhidi LIN
first_name: Zhidi
last_name: LIN
description: Personal website of Zhidi LIN.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with
  <a href="https://github.com/alshedivat/al-folio" target="_blank">al-folio</a>.
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.

lang: en
url: "https://zhidi-lin.github.io"
baseurl: ""
icon: hku_logo.jpg
max_width: 1000px

email: zhidilin@link.cuhk.edu.cn
github_username: zhidilin
twitter_username: Zhidi_LIN
linkedin_username: zhidi-lin
scholar_userid: 8BmRXqMAAAAJ&hl=en
orcid_id: 0000-0002-6673-511X
research_gate_profile: Zhidi-Lin
bluesky_id: zhidilin.bsky.social

google_analytics: G-G0CY8WV77Q

include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

plugins:
  - jekyll-sitemap

academicons:
  version: "1.9.1"
  integrity: "sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg="
bootstrap:
  version: "4.6.1"
  integrity:
    css: "sha256-DF7Zhf293AJxJNTmh5zhoYYIMs2oXitRfBjY+9L//AY="
    js: "sha256-fgLAgv7fyCGopR/gBNq2iW3ZKIdqIcyshnUULC4vex8="
fontawesome:
  version: "5.15.4"
  integrity: "sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4="
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
